from enum import Enum

# -----------------------SIZES----------------------------------------

# WIDTH = HEIGHT = *_SIZE
from pygame.rect import Rect

CHUNK_SIZE = 100
PLAYER_SIZE = 20
TILE_SIZE = 50

# Playable area
GAME_SCREEN_WIDTH = 1400
GAME_SCREEN_HEIGHT = 1080

GAME_SCREEN_RECT = Rect(0, 0, GAME_SCREEN_WIDTH, GAME_SCREEN_HEIGHT)

GAME_SCREEN_CENTER_X = GAME_SCREEN_WIDTH // 2
GAME_SCREEN_CENTER_Y = GAME_SCREEN_HEIGHT // 2

# Whole game window (With ui)
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

# ui (crafting and inventory)
UI_WIDTH  = SCREEN_WIDTH - GAME_SCREEN_WIDTH
UI_HEIGHT = SCREEN_HEIGHT

# -----------------------GAME-STATS------------------------------------

PLAYER_SPEED = 10

PLAYER_SCREEN_X = int(GAME_SCREEN_WIDTH / 2 - PLAYER_SIZE / 2)
PLAYER_SCREEN_Y = int(GAME_SCREEN_HEIGHT / 2 - PLAYER_SIZE / 2)

PLAYER_SCREEN_X_RAW = GAME_SCREEN_WIDTH / 2 - PLAYER_SIZE / 2
PLAYER_SCREEN_Y_RAW = GAME_SCREEN_HEIGHT / 2 - PLAYER_SIZE / 2


# Number of tiles that fit on the game screen + a little buffer
WIDTH_NO_OF_TILES  = GAME_SCREEN_WIDTH // TILE_SIZE + 2
HEIGHT_NO_OF_TILES = GAME_SCREEN_HEIGHT // TILE_SIZE + 2

# -----------------------MAP-GENERATION--------------------------------

# Trees, rocks, etc. to be placed on the map

# When generating the chunk, a random index is chosen
SPAWN_CHANCE_LIST = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2]

CHUNK_MIDDLE_OFFSET_I = 50
CHUNK_MIDDLE_OFFSET_J = 50

MIDDLE_SCREEN_I = HEIGHT_NO_OF_TILES // 2 // TILE_SIZE
MIDDLE_SCREEN_J = WIDTH_NO_OF_TILES // 2 // TILE_SIZE


class TileCode(Enum):
    GRASS = '0'
    ROCK  = '1'
    TREE  = '2'

    @staticmethod
    def get_description(value):

        value = int(value)

        if value == 0:
            return "Grass"
        elif value == 1:
            return "Some rocks"
        elif value == 2:
            return "A tree"


class Direction(Enum):
    DOWN  = 0
    UP    = 1
    LEFT  = 2
    RIGHT = 3


TILES_WITH_COLLIDERS = ['1', '2']
TILES_BUILDABLE = ['0']


# INVENTORY --------------------------------------

INVENTORY_CELL_SIZE = 80

# (x, y)
INVENTORY_TOP_LEFT = (GAME_SCREEN_WIDTH + 23, 560)
INVENTORY_BOT_LEFT = (GAME_SCREEN_WIDTH + 35, 1063)

INVENTORY_TOP_RIGHT = (GAME_SCREEN_WIDTH + 520, 560)
INVENTORY_BOT_RIGHT = (GAME_SCREEN_WIDTH + 485, 1063)

INVENTORY_SCREEN_WIDTH  = INVENTORY_TOP_RIGHT[0] - INVENTORY_TOP_LEFT[0]
INVENTORY_SCREEN_HEIGHT = INVENTORY_BOT_LEFT[1] - INVENTORY_TOP_LEFT[1]

INVENTORY_MATRIX_WIDTH  = INVENTORY_SCREEN_WIDTH  // INVENTORY_CELL_SIZE
INVENTORY_MATRIX_HEIGHT = INVENTORY_SCREEN_HEIGHT // INVENTORY_CELL_SIZE

INVENTORY_RECT = Rect(INVENTORY_TOP_LEFT[0], INVENTORY_TOP_LEFT[1], INVENTORY_SCREEN_WIDTH, INVENTORY_SCREEN_HEIGHT)

ITEM_STACK_SIZE = 5

# CRAFTING -----------------------------------------------------

CRAFTING_CELL_SIZE = 50

CRAFTING_TOP_LEFT = (GAME_SCREEN_WIDTH + 35, 20)
CRAFTING_BOT_LEFT = (GAME_SCREEN_WIDTH + 35, 441)

CRAFTING_TOP_RIGHT = (GAME_SCREEN_WIDTH + 485, 20)
CRAFTING_BOT_RIGHT = (GAME_SCREEN_WIDTH + 485, 441)

CRAFTING_SCREEN_WIDTH  = CRAFTING_TOP_RIGHT[0] - CRAFTING_TOP_LEFT[0]
CRAFTING_SCREEN_HEIGHT = CRAFTING_BOT_LEFT[1]  - CRAFTING_TOP_LEFT[1]

CRAFTING_MATRIX_WIDTH  = CRAFTING_SCREEN_WIDTH  // CRAFTING_CELL_SIZE
CRAFTING_MATRIX_HEIGHT = CRAFTING_SCREEN_HEIGHT // CRAFTING_CELL_SIZE


CRAFTING_RECT = Rect(CRAFTING_TOP_LEFT[0], CRAFTING_TOP_LEFT[1], CRAFTING_SCREEN_WIDTH, CRAFTING_SCREEN_HEIGHT)


# TOOLS --------------------------------------------------

TOOLS_CELL_WIDTH  = 50
TOOLS_CELL_HEIGHT = 82


TOOLS_TOP_LEFT = (GAME_SCREEN_WIDTH + 35, 460)
TOOLS_BOT_LEFT = (GAME_SCREEN_WIDTH + 35, 547)

TOOLS_TOP_RIGHT = (GAME_SCREEN_WIDTH + 485, 460)
TOOLS_BOT_RIGHT = (GAME_SCREEN_WIDTH + 485, 547)

TOOLS_SCREEN_WIDTH  = TOOLS_TOP_RIGHT[0] - TOOLS_TOP_LEFT[0]
TOOLS_SCREEN_HEIGHT = TOOLS_BOT_LEFT[1]  - TOOLS_TOP_LEFT[1]

TOOLS_WIDTH  = TOOLS_SCREEN_WIDTH  // TOOLS_CELL_WIDTH

TOOLS_RECT = Rect(TOOLS_TOP_LEFT[0], TOOLS_TOP_LEFT[1], TOOLS_SCREEN_WIDTH, TOOLS_SCREEN_HEIGHT)
